
services:
  dio-api:
    build:
      context: .
      dockerfile: Dockerfile
    command: ["/wait-for-it.sh", "147.93.71.60:3306", "-t", "60", "--", "java", "-jar", "/api.jar"]
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://147.93.71.60:3306/apiwhatsapp?createDatabaseIfNotExist=true
      SPRING_DATASOURCE_USERNAME: apiuser
      SPRING_DATASOURCE_PASSWORD: Dioge1997@
    networks:
      - dio-network
    ports:
      - "8080:8080"

  dio-proxy:
    build: ./nginx
    image: dio-proxy
    ports:
      - "81:81"
    networks:
      - dio-network

networks:
  dio-network:
    driver: bridge

